### ISSUE TITLE
Update PDE to ASM 9.3

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde.ui#11]
ASM 9.3 is released, with support for Java 19.
See https://asm.ow2.io/versions.html#9.3

We should update PDE to use it, once the bundle is in Orbit, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=579574

related bug for JDT is https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/8

**Comment by vogella** [comment]
@akurtakov is using Orbit still mandatory? Why not source it directly from Maven central via the Maven target integration?

**Comment by merks** [comment]
I expect SimRel will likely function better if folks reuse things from a common source.

**Comment by vogella** [comment]
> I expect SimRel will likely function better if folks reuse things from a common source.

Maven central is the common source even if Orbit is placed in between.

**Comment by mickaelistria** [comment]
We should now avoid Orbit unless there is a compelling reason to use it compared to getting the artifact from Central and PGP-signing it. It doesn't seem like it's the case here; shouldn't we just skip Orbit and use Maven Central libs (which happen to include decent MANIFEST.MF files) ?

**Comment by vogella** [comment]
Maven link seems to be https://search.maven.org/artifact/org.ow2.asm/asm/9.3/jar

**Comment by mickaelistria** [comment]
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/196 which adds upstream asm 9.3 to the target-platform.

**Comment by vogella** [comment]
Awesome @mickaelistria, no more waiting for Orbit necessary. One middle-man less.

**Comment by HannesWell** [comment]
While I agree that using libraries from Maven-Central directly is better, I wonder how we can ensure that not too many versions of the same library end up being used in SimRel? With Orbit there was only one (or at least few) versions that were used by all Eclipse projects. But what if we have a library that releases more frequently and has version 1.0, 1.1, 1.2, ... available and not all using projects have updated to the latest version?

For the Eclipse-SDK this problem is resolved because they use a shared TP (that Mickael just updated), isn't it?
For the pre-build Eclipse-Products provided by EPP (that are more than just the Eclipse-SDK) this should be resolved because when the product is assembled by Tycho/P2 only the latest available version is used unless a Plug-ins has a version range specified that is not satisfied by it. So I think here P2 tries to only install as few versions as possible?
And the `release`-p2-repos are just the union of all EPP-products, aren't they? Then it would be the same answer as above.

**Comment by mickaelistria** [comment]
>  not too many versions of the same library end up being used in SimRel?

That's more the problem of SimRel ;) But technically, things like version range work well to allow all projects to use same version of 1 lib, but still....

> With Orbit there was only one (or at least few) versions that were used by all Eclipse projects. But what if we have a library that releases more frequently and has version 1.0, 1.1, 1.2, ... available and not all using projects have updated to the latest version?

1 *per Orbit repository*, but Eclipse projects participating to SimRel didn't all rebuild against the same Orbit repo for the given SimRel, so those numerous projects could always have shipped different version of a lib than the one provided by latest Orbit. Basically, Orbit per se doesn't solve the problem of projects shipping different versions of the same lib in SimRel. As far as I know, this problem is actually not solved automatically, and not solved at all: looking at https://download.eclipse.org/releases/2022-03/202203161000/plugins/ lists multiple versions of eg gson, guava, com.google.inject, jna... Consuming from Central doesn't really make things worse.
But I would even challenge things further: is it even a problem to publish multiple versions of 1 lib if we can trust p2 to pick a good one according to what's necessary?

> So I think here P2 tries to only install as few versions as possible?

Yes, p2 director resolves to the smallest (as in least number of additional artifacts) provisioning plan that satisfies all given constraints.

**Comment by merks** [comment]
@HannesWell Yes, this is my only significant concern here, i.e., to reduce the number of duplicates.   The simrel repo is a union of all the requirements of all the repos of all the projects on the train.  Many projects use bundle requirements so even changes in the bundle IDs will very likely lead to yet more duplicates.   In the past we could say "use the versions from the current Orbit" but now we'll have to say use the same versions as the Platform and when it's not one used by the platform, use the same version as the other projects, which kind of becomes a circular definition.  So duplicate elimination/coordination will become more challenging... 

That's not an argument that we shouldn't do this, it's just an observation that with all good things most often there also come some not so good things...

**Comment by mickaelistria** [comment]
The rule that currently states "Build against latest milestone of Orbit" could then become "Build against latest milestone of Platform, Orbit and projects you depend on". But indeed, many project will like to directly do it the Maven way, and will introduce newer versions. Fortunately, as it's now easy to change versions, we can maybe just encourage all projects to always use latest versions (similarly to how they're encouraged to use latest Orbit repo at the moment), and the amount of duplication would remain manageable.

**Comment by HannesWell** [comment]
OK, good to know.
Yes, I also didn't want to argue against this change in workflow because I think it makes many things much simpler and allows faster adaption of new versions. As @merks said everything has a price, although it is lower now. And as @mickaelistria said in comment https://github.com/eclipse-pde/eclipse.pde.ui/issues/11#issuecomment-1090384292 this problem is not completely new and P2 should help here.

Maybe the combined SimRel could be scanned regularly for multiple versions and the contributing projects should be asked to update their dependencies, ideally with enough time to react before the final GA release (so at the milestones and RCs) and with good tooling support (doing this manually would be very cumbersome).

**Comment by laeubi** [comment]
Well actually maven central is also just a "bigger orbit" ... what would help indeed would be 

- https://github.com/dependabot/dependabot-core/issues/4682

So automated updates+automated checks+automated releases --> less versions and less manual work = more time for happy coding.

**Comment by mickaelistria** [comment]
Done with Done with https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/8f79635e7217ecb24dbc209b964711e66a8f322d

**Comment by iloveeclipse** [comment]
> Done with Done with [eclipse-platform/eclipse.platform.releng.aggregator@8f79635](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/8f79635e7217ecb24dbc209b964711e66a8f322d)

Nope, the version requirement in api tools should be updated too. I will push that.
